import type { Schematic } from '../schematic';
import { plot } from './plot';

export const MPU4VIDEO_SCHEMATIC: Schematic = plot({
  system: 'MPU4VIDEO',
  title: 'MPU4 VIDEO',
  source: 'Barcrest MPU4 Video - MC6809 + MC68000 - simplified board diagram',
  rows: [
    {
      kind: 'cells',
      band: 'edge',
      cells: [
        { id: 'lamps' },
        { id: 'switches' },
        { id: 'sevenseg' },
        { id: 'meters' },
        { id: 'triacs' },
        { id: 'coins' },
      ],
    },
    {
      kind: 'cells',
      band: 'io',
      cells: [
        { id: 'ic3' },
        { id: 'ic4' },
        { id: 'ic5' },
        { id: 'ic6' },
        { id: 'ic7' },
        { id: 'ic8' },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      cells: [
        { id: 'ram', span: 1 },
        { id: 'rom', span: 1.4 },
        { id: 'acia', span: 1.2 },
        { id: 'ptm', span: 1.2 },
        { id: 'ay', span: 0.9 },
        { id: 'alpha', span: 1.1 },
      ],
    },
    {
      kind: 'bus',
      rails: [
        { id: 'bus-data', label: 'DATA', rail: 'data' },
        { id: 'bus-addr', label: 'ADDRESS', rail: 'address' },
        { id: 'bus-ctrl', label: 'CONTROL', rail: 'control' },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      height: 60,
      cells: [
        { id: 'cpu', span: 2.2 },
        { id: 'ic23', span: 1.4 },
      ],
    },
    { kind: 'rail', id: 'link-rail', label: 'VIDEO LINK', rail: 'serial' },
    {
      kind: 'cells',
      band: 'core',
      cells: [
        { id: 'vacia', span: 1.1 },
        { id: 'vptm', span: 1.1 },
        { id: 'crtc', span: 1.2 },
        { id: 'palette', span: 1.1 },
        { id: 'saa', span: 1 },
        { id: 'chr', span: 1.2 },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      height: 60,
      cells: [
        { id: 'vcpu', span: 2.2 },
        { id: 'vrom', span: 1.2 },
        { id: 'vram', span: 1.2 },
      ],
    },
    {
      kind: 'cells',
      band: 'peripheral',
      cells: [
        { id: 'screen' },
        { id: 'coinmech' },
      ],
    },
  ],
  edges: [
    { from: 'lamps', to: 'ic3', kind: 'control' },
    { from: 'switches', to: 'ic8', kind: 'control' },
    { from: 'sevenseg', to: 'ic4', kind: 'control' },
    { from: 'meters', to: 'ic7', kind: 'control' },
    { from: 'triacs', to: 'ic8', kind: 'control' },
    { from: 'coins', to: 'ic5', kind: 'control' },
    { from: 'ic3', to: 'bus-data', kind: 'data' },
    { from: 'ic4', to: 'bus-data', kind: 'data' },
    { from: 'ic5', to: 'bus-data', kind: 'data' },
    { from: 'ic6', to: 'bus-data', kind: 'data' },
    { from: 'ic7', to: 'bus-data', kind: 'data' },
    { from: 'ic8', to: 'bus-data', kind: 'data' },
    { from: 'ram', to: 'bus-data', kind: 'data' },
    { from: 'ram', to: 'bus-addr', kind: 'address' },
    { from: 'rom', to: 'bus-data', kind: 'data' },
    { from: 'rom', to: 'bus-addr', kind: 'address' },
    { from: 'acia', to: 'bus-data', kind: 'data' },
    { from: 'ptm', to: 'bus-ctrl', kind: 'control' },
    { from: 'ay', to: 'bus-data', kind: 'data' },
    { from: 'alpha', to: 'bus-ctrl', kind: 'control' },
    { from: 'cpu', to: 'bus-data', kind: 'data' },
    { from: 'cpu', to: 'bus-addr', kind: 'address' },
    { from: 'cpu', to: 'bus-ctrl', kind: 'control' },
    { from: 'ic23', to: 'bus-ctrl', kind: 'control' },
    { from: 'acia', to: 'link-rail', kind: 'serial' },
    { from: 'link-rail', to: 'vacia', kind: 'serial' },
    { from: 'vptm', to: 'vacia', kind: 'control' },
    { from: 'vacia', to: 'vcpu', kind: 'data' },
    { from: 'vptm', to: 'vcpu', kind: 'control' },
    { from: 'crtc', to: 'vcpu', kind: 'control' },
    { from: 'palette', to: 'vcpu', kind: 'data' },
    { from: 'saa', to: 'vcpu', kind: 'data' },
    { from: 'chr', to: 'vcpu', kind: 'data' },
    { from: 'vrom', to: 'vcpu', kind: 'data' },
    { from: 'vram', to: 'vcpu', kind: 'data' },
    { from: 'crtc', to: 'screen', kind: 'data' },
    { from: 'palette', to: 'screen', kind: 'data' },
    { from: 'coins', to: 'coinmech', kind: 'control' },
  ],
});
