import type { Schematic } from '../schematic';
import { plot } from './plot';

export const MPU4_SCHEMATIC: Schematic = plot({
  system: 'MPU4',
  title: 'MPU4',
  source: 'Barcrest MPU4 - MC6809 - simplified board diagram',
  rows: [
    {
      kind: 'cells',
      band: 'edge',
      cells: [
        { id: 'lamps' },
        { id: 'switches' },
        { id: 'sevenseg' },
        { id: 'meters' },
        { id: 'triacs' },
        { id: 'coins' },
      ],
    },
    {
      kind: 'cells',
      band: 'io',
      cells: [
        { id: 'ic3' },
        { id: 'ic4' },
        { id: 'ic5' },
        { id: 'ic6' },
        { id: 'ic7' },
        { id: 'ic8' },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      cells: [
        { id: 'ram', span: 1 },
        { id: 'rom', span: 1.4 },
        { id: 'chr', span: 1.2 },
        { id: 'ptm', span: 1.2 },
        { id: 'ay', span: 0.9 },
        { id: 'oki', span: 1 },
        { id: 'alpha', span: 1.1 },
      ],
    },
    {
      kind: 'bus',
      rails: [
        { id: 'bus-data', label: 'DATA', rail: 'data' },
        { id: 'bus-addr', label: 'ADDRESS', rail: 'address' },
        { id: 'bus-ctrl', label: 'CONTROL', rail: 'control' },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      height: 60,
      cells: [
        { id: 'cpu', span: 2.2 },
        { id: 'ic23', span: 1.4 },
        { id: 'soundpia', span: 1.4 },
        { id: 'soundptm', span: 1.4 },
        { id: 'duart', span: 1.4 },
      ],
    },
    { kind: 'rail', id: 'periph-rail', label: 'CABINET LOOM', rail: 'serial' },
    {
      kind: 'cells',
      band: 'peripheral',
      cells: [
        { id: 'reels' },
        { id: 'hopper' },
        { id: 'coinmech' },
      ],
    },
  ],
  edges: [
    { from: 'lamps', to: 'ic3', kind: 'control' },
    { from: 'switches', to: 'ic8', kind: 'control' },
    { from: 'sevenseg', to: 'ic4', kind: 'control' },
    { from: 'meters', to: 'ic7', kind: 'control' },
    { from: 'triacs', to: 'ic8', kind: 'control' },
    { from: 'coins', to: 'ic5', kind: 'control' },
    { from: 'ic3', to: 'bus-data', kind: 'data' },
    { from: 'ic4', to: 'bus-data', kind: 'data' },
    { from: 'ic5', to: 'bus-data', kind: 'data' },
    { from: 'ic6', to: 'bus-data', kind: 'data' },
    { from: 'ic7', to: 'bus-data', kind: 'data' },
    { from: 'ic8', to: 'bus-data', kind: 'data' },
    { from: 'ram', to: 'bus-data', kind: 'data' },
    { from: 'ram', to: 'bus-addr', kind: 'address' },
    { from: 'rom', to: 'bus-data', kind: 'data' },
    { from: 'rom', to: 'bus-addr', kind: 'address' },
    { from: 'chr', to: 'bus-data', kind: 'data' },
    { from: 'ptm', to: 'bus-ctrl', kind: 'control' },
    { from: 'ay', to: 'bus-data', kind: 'data' },
    { from: 'oki', to: 'bus-data', kind: 'data' },
    { from: 'alpha', to: 'bus-ctrl', kind: 'control' },
    { from: 'cpu', to: 'bus-data', kind: 'data' },
    { from: 'cpu', to: 'bus-addr', kind: 'address' },
    { from: 'cpu', to: 'bus-ctrl', kind: 'control' },
    { from: 'ic23', to: 'bus-ctrl', kind: 'control' },
    { from: 'soundpia', to: 'bus-data', kind: 'data' },
    { from: 'soundptm', to: 'bus-ctrl', kind: 'control' },
    { from: 'duart', to: 'bus-data', kind: 'data' },
    { from: 'periph-rail', to: 'reels', kind: 'control' },
    { from: 'periph-rail', to: 'hopper', kind: 'serial' },
    { from: 'periph-rail', to: 'coinmech', kind: 'control' },
  ],
});
