import type { Schematic } from '../schematic';
import { plot } from './plot';

export const MPU5_SCHEMATIC: Schematic = plot({
  system: 'MPU5',
  title: 'MPU5',
  source: 'Barcrest MPU5 · MC68340 · simplified board diagram',
  rows: [
    {
      kind: 'cells',
      band: 'edge',
      cells: [
        { id: 'lamps' },
        { id: 'buttons' },
        { id: 'switches' },
        { id: 'sevenseg' },
        { id: 'meters' },
        { id: 'coins' },
      ],
    },
    { kind: 'cells', band: 'io', cells: [{ id: 'mux', span: 6.5 }, { id: 'vreg' }] },
    {
      kind: 'cells',
      band: 'core',
      cells: [
        { id: 'batt', span: 0.9 },
        { id: 'ram', span: 1.3 },
        { id: 'pal', span: 0.7 },
        { id: 'asic', span: 1.5 },
        { id: 'dsp', span: 1.1 },
        { id: 'dac', span: 0.8 },
        { id: 'amp', span: 0.8 },
      ],
    },
    {
      kind: 'bus',
      rails: [
        { id: 'bus-data', label: '16 DATA', rail: 'data' },
        { id: 'bus-addr', label: '24 ADDRESS', rail: 'address' },
        { id: 'bus-ctrl', label: 'CONTROL', rail: 'control' },
      ],
    },
    {
      kind: 'cells',
      band: 'core',
      height: 60,
      cells: [
        { id: 'cpu', span: 2.1 },
        { id: 'testport', span: 1.05 },
        { id: 'duart', span: 1.95 },
        { id: 'progcard', span: 2 },
      ],
    },
    {
      kind: 'cells',
      band: 'edge',
      cells: [
        { id: 'configkey' },
        { id: 'barbus' },
        { id: 'auxrs232' },
        { id: 'dataport' },
        { id: 'alpha' },
        { id: 'vendbus' },
        { id: 'secmeter' },
      ],
    },
    { kind: 'rail', id: 'periph-rail', label: 'CABINET LOOM', rail: 'serial' },
    {
      kind: 'cells',
      band: 'peripheral',
      cells: [
        { id: 'reels' },
        { id: 'hopper' },
        { id: 'coinmech' },
        { id: 'notes' },
      ],
    },
  ],
  edges: [
    { from: 'lamps', to: 'mux', kind: 'control' },
    { from: 'buttons', to: 'mux', kind: 'control' },
    { from: 'switches', to: 'mux', kind: 'control' },
    { from: 'sevenseg', to: 'mux', kind: 'control' },
    { from: 'meters', to: 'mux', kind: 'control' },
    { from: 'coins', to: 'mux', kind: 'control' },
    { from: 'mux', to: 'asic', kind: 'data' },
    { from: 'asic', to: 'dsp', kind: 'data' },
    { from: 'dsp', to: 'dac', kind: 'analog' },
    { from: 'dac', to: 'amp', kind: 'analog' },
    { from: 'ram', to: 'bus-data', kind: 'data' },
    { from: 'ram', to: 'bus-addr', kind: 'address' },
    { from: 'batt', to: 'bus-ctrl', kind: 'control' },
    { from: 'asic', to: 'bus-data', kind: 'data' },
    { from: 'asic', to: 'bus-addr', kind: 'address' },
    { from: 'pal', to: 'bus-ctrl', kind: 'control' },
    { from: 'cpu', to: 'bus-data', kind: 'data' },
    { from: 'cpu', to: 'bus-addr', kind: 'address' },
    { from: 'cpu', to: 'bus-ctrl', kind: 'control' },
    { from: 'duart', to: 'bus-data', kind: 'data' },
    { from: 'duart', to: 'bus-addr', kind: 'address' },
    { from: 'progcard', to: 'bus-data', kind: 'data' },
    { from: 'progcard', to: 'bus-ctrl', kind: 'control' },
    { from: 'testport', to: 'bus-ctrl', kind: 'control' },
    { from: 'cpu', to: 'configkey', kind: 'serial' },
    { from: 'cpu', to: 'barbus', kind: 'serial' },
    { from: 'testport', to: 'auxrs232', kind: 'serial' },
    { from: 'duart', to: 'dataport', kind: 'serial' },
    { from: 'duart', to: 'alpha', kind: 'serial' },
    { from: 'duart', to: 'vendbus', kind: 'serial' },
    { from: 'progcard', to: 'secmeter', kind: 'serial' },
    { from: 'periph-rail', to: 'reels', kind: 'serial' },
    { from: 'periph-rail', to: 'hopper', kind: 'control' },
    { from: 'periph-rail', to: 'coinmech', kind: 'control' },
    { from: 'periph-rail', to: 'notes', kind: 'serial' },
  ],
});
